# Minimal configuration with no linter rules

analyzer:
  errors:
    # Disable all warnings and hints
    unused_import: ignore
    dead_code: ignore
    missing_required_param: ignore
    missing_return: ignore
    unnecessary_cast: ignore
    unnecessary_new: ignore
    unnecessary_const: ignore

linter:
  rules:
    # Explicitly disable all linter rules
    avoid_print: false
    prefer_const_constructors: false
    # Add more rules to disable as needed
