name: sanatanpariwar
description: Sanatan Pariwar is a mobile application dedicated to promoting the values and teachings of Hinduism.

version: 9.1.1+7

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2


  # Firebase dependencies
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1


  # UI
  flutter_bloc: ^8.0.1
  http: ^1.1.2
  shared_preferences: ^2.0.10

  # Icons
  flutter_launcher_icons: ^0.13.1

  # Curved navigation bar
  curved_navigation_bar: ^1.0.3
  url_launcher: ^6.1.11
  font_awesome_flutter: ^10.4.0
  cached_network_image: ^3.2.3
  photo_view: ^0.14.0
  flutter_spinkit: ^5.2.0
  cloud_firestore: ^4.7.1
  firebase_messaging: ^14.6.1
  firebase_analytics: ^10.4.1
  country_picker: ^2.0.20
  intl: ^0.19.0
  flutter_local_notifications: ^16.2.0
  flutter_stripe: ^9.2.1
  pay: ^1.1.1
  pdf: ^3.10.4
  permission_handler: ^11.1.0
  open_file: ^3.3.1







  path_provider: any
  firebase_storage: ^11.7.6
  connectivity_plus: ^6.0.3
  flutter_cache_manager: ^3.3.2
  cached_firestorage: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo.png
    # Add your additional assets (images, fonts, etc.) here

  # Add any custom configurations, if required
