// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5LA-KNTW2MYB06cLaI5eYr7Aw53Ko3p0',
    appId: '1:772705405570:web:5498b0c3e1e4fca667829b',
    messagingSenderId: '772705405570',
    projectId: 'sanatan920',
    authDomain: 'sanatan920.firebaseapp.com',
    storageBucket: 'sanatan920.appspot.com',
    measurementId: 'G-K6B1BTEN6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQG_omS1VyiA57uaP0yPaUmmFFFS1VkY0',
    appId: '1:772705405570:android:2d98f23c0b0c00b467829b',
    messagingSenderId: '772705405570',
    projectId: 'sanatan920',
    storageBucket: 'sanatan920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyNfQiA4ur0vjRqNqhdqyQ0JMJsYN_g_k',
    appId: '1:772705405570:ios:7f91ca3cbfaa85c067829b',
    messagingSenderId: '772705405570',
    projectId: 'sanatan920',
    storageBucket: 'sanatan920.appspot.com',
    iosBundleId: 'com.sanatan.pariwar.sanatanpariwar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyNfQiA4ur0vjRqNqhdqyQ0JMJsYN_g_k',
    appId: '1:772705405570:ios:868200e1d2a56a6f67829b',
    messagingSenderId: '772705405570',
    projectId: 'sanatan920',
    storageBucket: 'sanatan920.appspot.com',
    iosBundleId: 'com.sanatan.pariwar.sanatanpariwar.RunnerTests',
  );
}
